ALTER TABLE `user_games` ADD UNIQUE (`account_id`);
ALTER TABLE `addresses` ADD `is_destroy_address` TINYINT(1) NOT NULL DEFAULT '0' AFTER `is_mine`;
UPDATE addresses SET is_destroy_address=1 WHERE option_index=0;
ALTER TABLE `transactions` DROP `OP_RETURN`, DROP `destroy_amount`;
ALTER TABLE `transaction_ios` DROP `destroy_amount`;
ALTER TABLE `events` CHANGE `event_name` `event_name` VARCHAR(255) CHARACTER SET latin1 COLLATE latin1_swedish_ci NULL DEFAULT NULL, CHANGE `option_name` `option_name` VARCHAR(255) CHARACTER SET latin1 COLLATE latin1_swedish_ci NULL DEFAULT NULL, CHANGE `option_name_plural` `option_name_plural` VARCHAR(255) CHARACTER SET latin1 COLLATE latin1_swedish_ci NULL DEFAULT NULL;
ALTER TABLE `addresses` ADD INDEX (`primary_blockchain_id`);
ALTER TABLE `games` CHANGE `min_unallocated_addresses` `min_unallocated_addresses` INT(11) NOT NULL DEFAULT '20';
UPDATE games SET min_unallocated_addresses=20;
ALTER TABLE `transaction_ios` ADD `is_destroy` TINYINT(1) NOT NULL DEFAULT '0' AFTER `out_index`;
UPDATE transaction_ios io JOIN addresses a ON io.address_id=a.address_id SET io.is_destroy=1 WHERE a.is_destroy_address=1;
