ALTER TABLE `games` CHANGE `inflation` `inflation` ENUM('linear','exponential','fixed_exponential') CHARACTER SET latin1 COLLATE latin1_swedish_ci NOT NULL DEFAULT 'linear';
UPDATE games SET inflation='fixed_exponential' WHERE inflation='exponential';
ALTER TABLE `games` CHANGE `payout_taper_function` `vote_effectiveness_function` ENUM('constant','linear_decrease') CHARACTER SET latin1 COLLATE latin1_swedish_ci NOT NULL DEFAULT 'constant';
ALTER TABLE `blocks` CHANGE `taper_factor` `effectiveness_factor` DECIMAL(9,8) NOT NULL DEFAULT '1.00000000';
ALTER TABLE `transactions` CHANGE `taper_factor` `effectiveness_factor` DECIMAL(9,8) NOT NULL DEFAULT '1.00000000';
ALTER TABLE `game_types` CHANGE `payout_taper_function` `vote_effectiveness_function` ENUM('constant','linear_decrease') CHARACTER SET latin1 COLLATE latin1_swedish_ci NOT NULL DEFAULT 'constant';
ALTER TABLE `cached_rounds` CHANGE `winning_score` `winning_votes` BIGINT(20) NOT NULL DEFAULT '0';
ALTER TABLE `cached_rounds` CHANGE `derived_winning_score` `derived_winning_votes` BIGINT(20) NOT NULL DEFAULT '0';
ALTER TABLE `cached_rounds` CHANGE `score_sum` `sum_votes` BIGINT(20) NOT NULL DEFAULT '0';
ALTER TABLE `cached_round_options` CHANGE `score` `votes` BIGINT(20) NOT NULL DEFAULT '0';
ALTER TABLE `cached_round_options` ADD `coin_score` BIGINT(20) NOT NULL DEFAULT '0' AFTER `rank`, ADD `coin_block_score` BIGINT(20) NOT NULL DEFAULT '0' AFTER `coin_score`, ADD `coin_round_score` BIGINT(20) NOT NULL DEFAULT '0' AFTER `coin_block_score`;